### ISSUE TITLE
General Startup Issue

### ISSUE THREAD

**Issue by mrsmithy121** [schdub/fg#1]
python fg.py
Traceback (most recent call last):
  File "fg.py", line 21, in <module>
    import fg_pb2
  File "/Users/osx/Downloads/fg-master/fg_pb2.py", line 23, in <module>
    \x18.GriffinMessages.Str_Flt\"\xbd\x06\n\x06Player\x12:\n\x10RandomGenerators\x18\x01 \x03(\x0b\x32 .GriffinMessages.RandomGenerator\x12.\n\nIapHistory\x18\x02 \x03(\x0b\x32\x1a.GriffinMessages.IAPRecord\x12-\n\tGiftCount\x18\x03 \x03(\x0b\x32\x1a.GriffinMessages.Str_Int32\x12\x39\n\x15\x42oosterPackStartTimes\x18\x04 \x03(\x0b\x32\x1a.GriffinMessages.Str_Int64\x12\x32\n\x0eOffersAccepted\x18\x05 \x03(\x0b\x32\x1a.GriffinMessages.Str_Int64\x12\x36\n\tInventory\x18\x06 \x03(\x0b\x32#.GriffinMessages.Inventory_TypePair\x12\x17\n\x0f\x43lickedModalIds\x18\x07 \x03(\t\x12\x19\n\x11LimitedShopoffers\x18\x08 \x01(\x05\x12\x1d\n\x15\x43onfirmedTransactions\x18\t \x01(\x05\x12\x17\n\x0fSentDeviceInfos\x18\n \x03(\t\x12\r\n\x05Level\x18\x10 \x01(\x01\x12\n\n\x02Xp\x18\x11 \x01(\x03\x12\x12\n\nXpAboveCap\x18\x12 \x01(\x03\x12\'\n\x06Wallet\x18\x13 \x01(\x0b\x32\x17.GriffinMessages.Wallet\x12\x33\n\x05Goals\x18\x14 \x01(\x0b\x32$.GriffinMessages.GoalProgressManager\x12=\n\x0e\x46\x65\x61turedModals\x18\x15 \x01(\x0b\x32%.GriffinMessages.FeaturedModalManager\x12\x1b\n\x13LastViewedOfferwall\x18\x16 \x01(\x03\x12\x36\n\nTimedPromo\x18\x17 \x01(\x0b\x32\".GriffinMessages.TimedPromoManager\x12/\n\nGameCenter\x18\x18 \x01(\x0b\x32\x1b.GriffinMessages.GameCenter\x12\x33\n\x0c\x41\x63hievements\x18\x19 \x01(\x0b\x32\x1d.GriffinMessages.Achievements*\x8e\x01\n\tGoalState\x12\x12\n\x0eGOALNOTSTARTED\x10\x01\x12\x12\n\x0eGOALINCOMPLETE\x10\x02\x12\x18\n\x14GOALREQUIREDCOMPLETE\x10\x03\x12\x18\n\x14GOALOPTIONALCOMPLETE\x10\x04\x12\x15\n\x11GOALFULLYCOMPLETE\x10\x05\x12\x0e\n\nGOALFAILED\x10\x06')
TypeError: __init__() got an unexpected keyword argument 'syntax'

**Comment by schdub** [comment]
@mrsmithy121, version of your protobuf library for Python? Open python interpreter and enter:

    import google.protobuf
    google.protobuf.__version__

**Comment by schdub** [comment]
@mrsmithy121 please try latest changes.

**Comment by mrsmithy121** [comment]
Fixed thank you
