### ISSUE TITLE
Login Uid Issue

### ISSUE THREAD

**Issue by Family-Guy1** [schdub/fg#3]
When I try my id, I get this:

{"appid": "com.tinycorp.familyguy.android", "software_version": "1.15.0", "locale": "en_US", "install_id": -826558170, "android_identifiers": {"RANDOM_ID": "bd9sfg4n96me2a1b8on8302412qr6rtp", "referrer_str": "", "idfa": "a149be51-4cf4-43e8-997d-901424a64a93", "SERIAL_ID": "9cb99771", "IMEI_ID": "352397050392277", "ANDROID_ID": "f853b2be1d78eb3e"}, "client_timestamp": 1462245676, "session": "5d18341f3e87bb93fbaca3a8f69ccdf4", "device_model_name": "LG-E612", "player_id": "uid", "device_manufacturer": "LGE", "run_number_this_version": 5, "ip_address": "FE80::2AA:70FF:FED4:706E", "starting_free_memory": 3, "device_id": "352397050392277", "run_number": 5, "language": "en", "memory_cap": 48, "level": 0, "device_model": "m4", "native_memory_cap": 390, "identifier_type": "IMEI_ID", "timezone_gmt_offset": 14400, "network_link_Mbps": 54, "os_version": "15", "network_info": "Wi-Fi", "data": [["login", {"sk": "", "fbt": ""}], ["config", {"locale": "en_US", "country": "US", "preferred": "", "language": "en", "fullLocale": "en_US"}, {"salt": "[1462245680.53,\"0703453034c53a996e1175cc69df2a7b\"].NAR5m-Cnx5qfEwM4HwARiCcKMNI", "signature": "53810aef211cb0bdf12c96b763b41667"}], ["getGameStatePB", ""], ["getTransactionSummary"]], "country": "US", "num_attempts": 0, "os_type": "android", "human_id": ""}
67e579de4c71609a4de941e3b8a40937
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): familyguy.tinyco.com
C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py:821: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
DEBUG:requests.packages.urllib3.connectionpool:"POST /tapservice/api/ HTTP/1.1" 400 11
Bad Request
Traceback (most recent call last):
  File "C:\Users\FamilyGuy\Downloads\fg-master\fg-master\fg.py", line 334, in <module>
    func(args)
  File "C:\Users\FamilyGuy\Downloads\fg-master\fg-master\fg.py", line 163, in doLogin
    for o in json.loads(self.doApiRequest(req))['response']:
  File "C:\Python27\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
None

**Comment by schdub** [comment]
@Family-Guy1 contact my email. I need your UID. It's looks like you've entered uid instead your real id.
